### ISSUE TITLE
Underscore vs Lodash

### ISSUE THREAD

**Issue by jeffski** [svdgraaf/serverless-plugin-stage-variables#1]
The package.json defines the dependency as underscore but src/index.js does require('lodash');

When I do `sls deploy` I get **'Cannot find module 'lodash'** error.

When I installed lodash then it worked.

**Comment by svdgraaf** [comment]
I was way behind on github notifications, so only just found these issues. The mentioned PR is merged, and I just releases a new revision v1.7.7 which includes this change.

Sorry for the delay!
