### ISSUE TITLE
Cannot read property 'cli' of undefined

### ISSUE THREAD

**Issue by cs17** [svdgraaf/serverless-plugin-stage-variables#25]
We encountered this problem in Version 1.9.3 that just released yesterday. 

`/codebuild/output/src123456789/src/serverless/sampleproject: 
Serverless: Packaging service... 
Serverless: Excluding development dependencies... 
Serverless: Excluding development dependencies... 
Serverless: Excluding development dependencies... 
  
  Type Error --------------------------------------------- 
  
  Cannot read property 'cli' of undefined 
  
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable. 
  
  Get Support -------------------------------------------- 
     Docs:          docs.serverless.com 
     Bugs:          github.com/serverless/serverless/issues 
     Issues:        forum.serverless.com 
  
  Your Environment Information ----------------------------- 
     OS:                     linux 
     Node Version:           10.14.1 
     Serverless Version:     1.38.0 
  `

P/s: we switch back to the previous version and it's working.

**Comment by svdgraaf** [comment]
@cheesiangcs that 1.38 is pretty old.

I think I've found the issue, and I just released a new verison. Can you confirm it's fixed by installing 1.9.4?

**Comment by cs17** [comment]
@svdgraaf Thanks for your help :)

I encountered a new error now...

`Type Error --------------------------------------------- 
  
  Cannot read property '_serverless' of undefined `

**Comment by vallyscode** [comment]
I have found the place with problem, will add pull request with fix in few minutes
#27

**Comment by svdgraaf** [comment]
I've released 1.9.5 from #27 , please check if that fixes your issue @cheesiangcs

**Comment by cs17** [comment]
prefect, it's now working! Thanks @svdgraaf
