### ISSUE TITLE
TypeError: Cannot read property 'restApiId' of undefined

### ISSUE THREAD

**Issue by jweyrich** [svdgraaf/serverless-plugin-stage-variables#38]
Commit https://github.com/svdgraaf/serverless-plugin-stage-variables/commit/9da937c88800bf86ca461a31b23a703255d3ff37 is causing the error shown in the screenshot below:

![image](https://user-images.githubusercontent.com/206930/143496104-3ade49aa-5da3-4b83-a4a5-ef5b8b03953d.png)

**Comment by gastonpereyra** [comment]
I have the same problem.

**Comment by manuelvilche** [comment]
Same here!! 😔

**Comment by medikoo** [comment]
Great thanks for report, fixed with https://github.com/svdgraaf/serverless-plugin-stage-variables/commit/8919292a286df3f32164fb4489c0c06f32636984 and published with v1.10.1
